[package]
name = "ziwaan"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "alloc", "dev_urandom_fallback" ]
alloc = []
dev_urandom_fallback = []
std = []
wasm32_c = []

[dependencies]
untrusted = "0.7"

fiat-crypto = "0.1"
aes = "0.8"
chacha20 = "0.9"
chacha20poly1305 = "0.9"
aes-gcm = "0.9"
aead = "0.4"
sha1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
pkcs8 = "0.8"
pbkdf2 = "0.10"
rsa = "0.5"
getrandom = "0.2"
subtle = "2"
