[package]
name = "ziwaan"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "alloc", "dev_urandom_fallback" ]
alloc = []
dev_urandom_fallback = []
std = []
wasm32_c = []

[dependencies]
untrusted = "0.7"

# aead
aes = "0.8"
chacha20 = "0.9"
chacha20poly1305 = "0.9"
aes-gcm = "0.9"
aead = "0.4"

# digest
sha1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
pbkdf2 = "0.10"

# agreement & signature
curve25519-dalek = "3"
ed25519-dalek = "1"
x25519-dalek = "1"
p256 = "0.10"
p384 = "0.9"
elliptic-curve = { version = "0.11", features = [ "ecdh" ] }
ed25519 = "1"
ecdsa = "0.13"
rsa = "0.5"
sha2_09 = { package = "sha2", version = "0.9" } # p256 dependence

# util
getrandom = "0.2"
subtle = "2"
